/* The InstallSingleTableIT should show that a given table install works, so just create an
   environment with as few variables as possible to show every table got installed. */

/* Drop all testsrc swap tables. */
drop table if exists wqp.act_metric_swap_testsrc;
drop table if exists wqp.activity_sum_swap_testsrc;
drop table if exists wqp.activity_swap_testsrc;
drop table if exists wqp.assemblage_swap_testsrc;
drop table if exists wqp.bio_hab_metric_swap_testsrc;
drop table if exists wqp.char_name_swap_testsrc;
drop table if exists wqp.char_type_swap_testsrc;
drop table if exists wqp.country_swap_testsrc;
drop table if exists wqp.county_swap_testsrc;
drop table if exists wqp.ml_grouping_swap_testsrc;
drop table if exists wqp.monitoring_loc_swap_testsrc;
drop table if exists wqp.org_data_swap_testsrc;
drop table if exists wqp.org_grouping_swap_testsrc;
drop table if exists wqp.organization_sum_swap_testsrc;
drop table if exists wqp.organization_swap_testsrc;
drop table if exists wqp.prj_ml_weighting_swap_testsrc;
drop table if exists wqp.project_data_swap_testsrc;
drop table if exists wqp.project_dim_swap_testsrc;
drop table if exists wqp.project_swap_testsrc;
drop table if exists wqp.qwportal_summary_swap_testsrc;
drop table if exists wqp.r_detect_qnt_lmt_swap_testsrc;
drop table if exists wqp.result_sum_swap_testsrc;
drop table if exists wqp.result_swap_testsrc;
drop table if exists wqp.sample_media_swap_testsrc;
drop table if exists wqp.site_type_swap_testsrc;
drop table if exists wqp.state_swap_testsrc;
drop table if exists wqp.station_sum_swap_testsrc;
drop table if exists wqp.station_swap_testsrc;
drop table if exists wqp.taxa_name_swap_testsrc;

/* And replace them without indexes. */
select create_swap_table ('testsrc', 'wqp', 'act_metric');
select create_swap_table ('testsrc', 'wqp', 'activity_sum');
select create_swap_table ('testsrc', 'wqp', 'activity');
select create_swap_table ('testsrc', 'wqp', 'assemblage');
select create_swap_table ('testsrc', 'wqp', 'bio_hab_metric');
select create_swap_table ('testsrc', 'wqp', 'char_name');
select create_swap_table ('testsrc', 'wqp', 'char_type');
select create_swap_table ('testsrc', 'wqp', 'country');
select create_swap_table ('testsrc', 'wqp', 'county');
select create_swap_table ('testsrc', 'wqp', 'ml_grouping');
select create_swap_table ('testsrc', 'wqp', 'monitoring_loc');
select create_swap_table ('testsrc', 'wqp', 'org_data');
select create_swap_table ('testsrc', 'wqp', 'org_grouping');
select create_swap_table ('testsrc', 'wqp', 'organization_sum');
select create_swap_table ('testsrc', 'wqp', 'organization');
select create_swap_table ('testsrc', 'wqp', 'prj_ml_weighting');
select create_swap_table ('testsrc', 'wqp', 'project_data');
select create_swap_table ('testsrc', 'wqp', 'project_dim');
select create_swap_table ('testsrc', 'wqp', 'project');
select create_swap_table ('testsrc', 'wqp', 'qwportal_summary');
select create_swap_table ('testsrc', 'wqp', 'r_detect_qnt_lmt');
select create_swap_table ('testsrc', 'wqp', 'result_sum');
select create_swap_table ('testsrc', 'wqp', 'result');
select create_swap_table ('testsrc', 'wqp', 'sample_media');
select create_swap_table ('testsrc', 'wqp', 'site_type');
select create_swap_table ('testsrc', 'wqp', 'state');
select create_swap_table ('testsrc', 'wqp', 'station_sum');
select create_swap_table ('testsrc', 'wqp', 'station');
select create_swap_table ('testsrc', 'wqp', 'taxa_name');

/* Drop all testsrc partitions. */
drop table if exists wqp.act_metric_testsrc;
drop table if exists wqp.activity_sum_testsrc;
drop table if exists wqp.activity_testsrc;
drop table if exists wqp.assemblage_testsrc;
drop table if exists wqp.bio_hab_metric_testsrc;
drop table if exists wqp.char_name_testsrc;
drop table if exists wqp.char_type_testsrc;
drop table if exists wqp.country_testsrc;
drop table if exists wqp.county_testsrc;
drop table if exists wqp.ml_grouping_testsrc;
drop table if exists wqp.monitoring_loc_testsrc;
drop table if exists wqp.org_data_testsrc;
drop table if exists wqp.org_grouping_testsrc;
drop table if exists wqp.organization_sum_testsrc;
drop table if exists wqp.organization_testsrc;
drop table if exists wqp.prj_ml_weighting_testsrc;
drop table if exists wqp.project_data_testsrc;
drop table if exists wqp.project_dim_testsrc;
drop table if exists wqp.project_testsrc;
drop table if exists wqp.qwportal_summary_testsrc;
drop table if exists wqp.r_detect_qnt_lmt_testsrc;
drop table if exists wqp.result_sum_testsrc;
drop table if exists wqp.result_testsrc;
drop table if exists wqp.sample_media_testsrc;
drop table if exists wqp.site_type_testsrc;
drop table if exists wqp.state_testsrc;
drop table if exists wqp.station_sum_testsrc;
drop table if exists wqp.station_testsrc;
drop table if exists wqp.taxa_name_testsrc;

/* And replace them without indexes. */
create table if not exists wqp.act_metric_testsrc partition of wqp.act_metric for values in (0);
create table if not exists wqp.activity_sum_testsrc partition of wqp.activity_sum for values in (0);
create table if not exists wqp.activity_testsrc partition of wqp.activity for values in (0);
create table if not exists wqp.assemblage_testsrc partition of wqp.assemblage for values in (0);
create table if not exists wqp.bio_hab_metric_testsrc partition of wqp.bio_hab_metric for values in (0);
create table if not exists wqp.char_name_testsrc partition of wqp.char_name for values in (0);
create table if not exists wqp.char_type_testsrc partition of wqp.char_type for values in (0);
create table if not exists wqp.country_testsrc partition of wqp.country for values in (0);
create table if not exists wqp.county_testsrc partition of wqp.county for values in (0);
create table if not exists wqp.ml_grouping_testsrc partition of wqp.ml_grouping for values in (0);
create table if not exists wqp.monitoring_loc_testsrc partition of wqp.monitoring_loc for values in (0);
create table if not exists wqp.org_data_testsrc partition of wqp.org_data for values in (0);
create table if not exists wqp.org_grouping_testsrc partition of wqp.org_grouping for values in (0);
create table if not exists wqp.organization_sum_testsrc partition of wqp.organization_sum for values in (0);
create table if not exists wqp.organization_testsrc partition of wqp.organization for values in (0);
create table if not exists wqp.prj_ml_weighting_testsrc partition of wqp.prj_ml_weighting for values in (0);
create table if not exists wqp.project_data_testsrc partition of wqp.project_data for values in (0);
create table if not exists wqp.project_dim_testsrc partition of wqp.project_dim for values in (0);
create table if not exists wqp.project_testsrc partition of wqp.project for values in (0);
create table if not exists wqp.qwportal_summary_testsrc partition of wqp.qwportal_summary for values in (0);
create table if not exists wqp.r_detect_qnt_lmt_testsrc partition of wqp.r_detect_qnt_lmt for values in (0);
create table if not exists wqp.result_sum_testsrc partition of wqp.result_sum for values in (0);
create table if not exists wqp.result_testsrc partition of wqp.result for values in (0);
create table if not exists wqp.sample_media_testsrc partition of wqp.sample_media for values in (0);
create table if not exists wqp.site_type_testsrc partition of wqp.site_type for values in (0);
create table if not exists wqp.state_testsrc partition of wqp.state for values in (0);
create table if not exists wqp.station_sum_testsrc partition of wqp.station_sum for values in (0);
create table if not exists wqp.station_testsrc partition of wqp.station for values in (0);
create table if not exists wqp.taxa_name_testsrc partition of wqp.taxa_name for values in (0);

/* Make sure all _old tables exist, otherwise dbunit cries. */
create table if not exists wqp.act_metric_testsrc_old (like wqp.act_metric_testsrc);
create table if not exists wqp.activity_sum_testsrc_old (like wqp.activity_sum_testsrc);
create table if not exists wqp.activity_testsrc_old (like wqp.activity_testsrc);
create table if not exists wqp.assemblage_testsrc_old (like wqp.assemblage_testsrc);
create table if not exists wqp.bio_hab_metric_testsrc_old (like wqp.bio_hab_metric_testsrc);
create table if not exists wqp.char_name_testsrc_old (like wqp.char_name_testsrc);
create table if not exists wqp.char_type_testsrc_old (like wqp.char_type_testsrc);
create table if not exists wqp.country_testsrc_old (like wqp.country_testsrc);
create table if not exists wqp.county_testsrc_old (like wqp.county_testsrc);
create table if not exists wqp.ml_grouping_testsrc_old (like wqp.ml_grouping_testsrc);
create table if not exists wqp.monitoring_loc_testsrc_old (like wqp.monitoring_loc_testsrc);
create table if not exists wqp.org_data_testsrc_old (like wqp.org_data_testsrc);
create table if not exists wqp.org_grouping_testsrc_old (like wqp.org_grouping_testsrc);
create table if not exists wqp.organization_sum_testsrc_old (like wqp.organization_sum_testsrc);
create table if not exists wqp.organization_testsrc_old (like wqp.organization_testsrc);
create table if not exists wqp.prj_ml_weighting_testsrc_old (like wqp.prj_ml_weighting_testsrc);
create table if not exists wqp.project_data_testsrc_old (like wqp.project_data_testsrc);
create table if not exists wqp.project_dim_testsrc_old (like wqp.project_dim_testsrc);
create table if not exists wqp.project_testsrc_old (like wqp.project_testsrc);
create table if not exists wqp.qwportal_summary_testsrc_old (like wqp.qwportal_summary_testsrc);
create table if not exists wqp.r_detect_qnt_lmt_testsrc_old (like wqp.r_detect_qnt_lmt_testsrc);
create table if not exists wqp.result_sum_testsrc_old (like wqp.result_sum_testsrc);
create table if not exists wqp.result_testsrc_old (like wqp.result_testsrc);
create table if not exists wqp.sample_media_testsrc_old (like wqp.sample_media_testsrc);
create table if not exists wqp.site_type_testsrc_old (like wqp.site_type_testsrc);
create table if not exists wqp.state_testsrc_old (like wqp.state_testsrc);
create table if not exists wqp.station_sum_testsrc_old (like wqp.station_sum_testsrc);
create table if not exists wqp.station_testsrc_old (like wqp.station_testsrc);
create table if not exists wqp.taxa_name_testsrc_old (like wqp.taxa_name_testsrc);

/* Make sure all _old tables are empty. */
truncate table wqp.act_metric_testsrc_old;
truncate table wqp.activity_sum_testsrc_old;
truncate table wqp.activity_testsrc_old;
truncate table wqp.assemblage_testsrc_old;
truncate table wqp.bio_hab_metric_testsrc_old;
truncate table wqp.char_name_testsrc_old;
truncate table wqp.char_type_testsrc_old;
truncate table wqp.country_testsrc_old;
truncate table wqp.county_testsrc_old;
truncate table wqp.ml_grouping_testsrc_old;
truncate table wqp.monitoring_loc_testsrc_old;
truncate table wqp.org_data_testsrc_old;
truncate table wqp.org_grouping_testsrc_old;
truncate table wqp.organization_sum_testsrc_old;
truncate table wqp.organization_testsrc_old;
truncate table wqp.prj_ml_weighting_testsrc_old;
truncate table wqp.project_data_testsrc_old;
truncate table wqp.project_dim_testsrc_old;
truncate table wqp.project_testsrc_old;
truncate table wqp.qwportal_summary_testsrc_old;
truncate table wqp.r_detect_qnt_lmt_testsrc_old;
truncate table wqp.result_sum_testsrc_old;
truncate table wqp.result_testsrc_old;
truncate table wqp.sample_media_testsrc_old;
truncate table wqp.site_type_testsrc_old;
truncate table wqp.state_testsrc_old;
truncate table wqp.station_sum_testsrc_old;
truncate table wqp.station_testsrc_old;
truncate table wqp.taxa_name_testsrc_old;
