sudo: true

language: java

services:
  - docker

jdk:
  - openjdk11

install: true

script:
  - docker network create wqpEtlCore
  - docker run --rm \ -v /var/run/docker.sock:/var/run/docker.sock -v "$TRAVIS_BUILD_DIR":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.0-jdk-11 mvn clean verify
  - docker network rm wqpEtlCore
