sudo: true

language: java

services:
  - docker

jdk:
  - openjdk11

install: true

script:
  - docker network create wqpEtlCore
  - mvn verify -Dlogging.level.root=ERROR
  - docker network rm wqpEtlCore
